### ISSUE TITLE
Submit (and Save) Questionnaires

### ISSUE THREAD

**Issue by YouriVerveld** [meddbase/meddbase-apis#18]
Hi,

We would like the participants in our application to also fill in the questionnaires linked to the appointments. Based on the Appointment that is booked, we retrieve the associated open questionnaires using the key. Using the Get Appointment Details, we then fetch all the details. These questionnaires are then filled out by the participant, and we want to submit them to Meddbase. We would like to use the URL:

https://{{api-host}}/patientportalapi/appointment/save-submit-questionnaire

We enter the Questionnaire Key in the questionnaire parameter. However, we keep receiving an error stating that the questionnaire key is not valid. Even if we only fill in the save (i.e., it doesn’t matter whether all the required questions are filled out), we still get the same error.

Please find attached the request and the response. How should we provide the body exactly, and why do we keep getting the message that the questionnaire key is not valid? We are using the same key as for the get questionnaire details.

[ResponseSaveAndSubmitQuestionnaire.json](https://github.com/user-attachments/files/18072524/ResponseSaveAndSubmitQuestionnaire.json)
[RequestSaveAndSubmitQuestionnaire.json](https://github.com/user-attachments/files/18072525/RequestSaveAndSubmitQuestionnaire.json)
[URLSaveAndSubmitQuestionnaire.json](https://github.com/user-attachments/files/18072526/URLSaveAndSubmitQuestionnaire.json)
[ResponseQuestionnaireDetails.json](https://github.com/user-attachments/files/18072527/ResponseQuestionnaireDetails.json)

**Comment by JoshAdams-Meddbase** [comment]
The documentation page for the [SaveAndSubmitQuestionnaire](https://meddbase.github.io/meddbase-apis/patient-portal-api/appointments/saveandsubmitquestionnaire.html) API is currently incorrect. It lists the `questionnaire` and `answers` parameters as being URL Parameters which is wrong, these should be part of the JSON POST data instead. In the sample you have provided the `questionnaire` key should be moved from the URL into the POST body and the `QuestionnaireAnswerData` key should be  `answers` instead. The structure should look like the following example:
```json
{
    "questionnaire": "q13788",
    "answers": [
        {
            "QuestionId": 236,
            "Answer": "Yes"
        },
        {
            "QuestionId": 237,
            "Answer": "No"
        }
    ]
}
```

A [pull request](https://github.com/meddbase/meddbase-apis/pull/21) has been raised to correct the **SaveAndSubmitQuestionnaire** docs and to include a POST data example, thank you for highlighting this issue.

**Comment by YouriVerveld** [comment]
Thank you for your response. I’ve managed to get a questionnaire submitted via Postman based on your answer. Thanks again!
